name: Build Android APK
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    # Запускаем сборку внутри официального изолированного контейнера Kivy
    container: kivy/buildozer:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        run: |
          # Внутри контейнера уже есть всё необходимое, просто запускаем компиляцию
          export BUILDOZER_ALLOW_ROOT_ERRORS=1
          yes | buildozer android debug
        env:
          TERM: xterm

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Polniy-Strategy-APK
          path: bin/*.apk
